### ISSUE TITLE
minecraftctl

### ISSUE THREAD

**Issue by MemoryShadow** [MemoryShadow/minecraftctl#3]
- [ ] 写minecraftctl的存档切换功能
- [ ] 写minecraftctl-install命令
  - [ ] 支持官方服务端下载地址查询/获取
      ```bash
      # 或许我可以用这个
      echo `curl -s https://mcversions.net/download/1.12.2 | xmllint --html --xpath '//div[@class="downloads block lg:flex lg:mt-0 p-8 md:p-12 md:pr-0 lg:col-start-1"]/div[1]/a/@href' - 2> /dev/null`
      ```
  - [ ] 支持Bukkit下载地址查询/获取
  - [ ] 支持Spigot自动构建部署
  - [x] 支持Paper下载地址查询/获取
  - [ ] 支持Mohist下载地址查询/获取
  - [ ] 支持airplane下载地址查询/获取
  - [ ] 支持Sponge下载地址查询/获取
- [ ] 写minecraftctl用户消息获取功能
- [ ] 写minecraftctl的简单UI界面

**Comment by MemoryShadow** [comment]
咕完这些功能就打2.0的tag上去

**Comment by MemoryShadow** [comment]
下下个版本准备的功能: [NBT相关处理](https://wiki.biligame.com/mc/%E6%95%99%E7%A8%8B/%E8%BF%90%E8%A1%8C%E6%95%B0%E6%8D%AE%E7%94%9F%E6%88%90%E5%99%A8#NBT%E6%96%87%E4%BB%B6%E8%BD%AC%E6%8D%A2%E4%B8%BASNBT%E6%96%87%E4%BB%B6)

**Comment by MemoryShadow** [comment]
## TODO(鸽子画饼) v1.2.0. GO!

- [x] 写minecraftctl-install命令
  - [x] 支持官方服务端下载地址查询/获取
    > 感谢BMCLAPI提供的镜像服务[https://bmclapidoc.bangbang93.com/](https://afdian.net/@bangbang93 "如果你想要赞助BMCLAPI，请点击这个链接")
  - [x] 支持[Forge](https://files.minecraftforge.net/net/minecraftforge/forge/ "点击前往")下载地址查询/获取
    > 感谢BMCLAPI提供的镜像服务[https://bmclapidoc.bangbang93.com/](https://afdian.net/@bangbang93 "如果你想要赞助BMCLAPI，请点击这个链接")
  - [x] 支持[authlib injector](https://github.com/yushijinhun/authlib-injector "点击前往")下载地址查询/获取
    > 感谢BMCLAPI提供的镜像服务[https://bmclapidoc.bangbang93.com/](https://afdian.net/@bangbang93 "如果你想要赞助BMCLAPI，请点击这个链接")
  - [x] 支持[Paper](https://papermc.io/ "点击前往")下载地址查询/获取
  - [x] 支持[Purpur](https://purpurmc.org/ "点击前往")下载地址查询/获取
  - [x] 支持[Mohist](https://mohistmc.com/ "点击前往")下载地址查询/获取
  - [x] 支持[Bukkit](https://dev.bukkit.org "点击前往")自动构建
    - [x] #5
  - [x] 支持[Spigot](https://www.spigotmc.org/ "点击前往")自动构建
    - [x] #5
  - [x] 支持[Cat](https://github.com/Luohuayu/CatServer "点击前往")下载地址查询/获取
  > 参阅[此处文档](https://www.codenong.com/18995854/ "点击前往")，可得[此API](https://api.github.com/repos/Luohuayu/CatServer/releases "点击前往")，此处可获得对应的下载链接，同时，此处还有官网的国内国外两个下载镜像
- [x] #13
  - [x] listen核心代码
  - [x] 事件抽象
  - [x] 插件接口支持
- [x] 写minecraftctl的备份/存档切换功能
  - [x] 备份功能
  - [x] #8
    - [x] 完全回档
    - ~~回档玩家信息~~(v1.3.0)
    - ~~回档指定区块文件~~(v1.3.0)
- [x] 编写几个特殊参数: -V, -h, -A(bout)
- [x] 写minecraftctl的简单UI界面
  - [x] 提供可供操作的小界面
- [x] 添加i18n支持
- [x] 添加自动补全功能
- [x] Fix: #1

~支持[airplane](https://github.com/TECHNOVE/Airplane "点击前往")下载地址查询/获取(官网似乎出了点问题)~
  > ![图片](https://user-images.githubusercontent.com/31596045/202834403-664a4d0b-84d3-4f52-a07f-bfd21ef8176f.png)

~支持[Sponge](https://github.com/SpongePowered/SpongeForge "点击前往")下载地址查询/获取(项目似乎只有低版本，向后延迟)~
